build: false

environment:
  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\continuous-integration\\appveyor\\run_with_env.cmd"
  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

install:
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install -U -r requirements.txt"

test_script:
  - "copy config_example.py config.py"
  - "%PYTHON%\\python.exe run.py"
